/* CLI Course Hub — shared course engine. Ported from WinBox_curse. Vanilla JS, offline (file://), no dependencies.
   Source of truth: cli-course-hub/engine/. Copies in courses/<id>/engine/ are generated by scripts/sync-engine.sh — do not edit them. */
(function () {
  'use strict';

  var ICONS = window.WB_ICONS || {};
  var CFG = window.CLI_COURSE_CONFIG || {};
  var COURSE_TITLE = String(CFG.title || 'CLI-курс');
  var STORAGE_KEY = String(CFG.storageKey || ('cli-' + (CFG.id || 'course') + '-v1'));
  var LESSON_PASS = 70;
  var PROMPT = String(CFG.prompt || '$');
  var CASE_INSENSITIVE = CFG.caseInsensitive === true;
  var reducedMotion = window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;


  /* ---------- helpers ---------- */
  function esc(v) {
    return String(v == null ? '' : v)
      .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
  }
  // Escaped plain text with `inline code` and **bold** support. Used for every non-body string.
  function rt(v) {
    return esc(v).replace(/`([^`\n]+)`/g, '<code>$1</code>').replace(/\*\*([^*\n]+)\*\*/g, '<strong>$1</strong>');
  }
  // Trusted HTML if the author used tags, otherwise plain text.
  function rich(v) { var s = str(v); return /<[a-z][^>]*>/i.test(s) ? wrapTables(s) : rt(s); }
  // Wide author tables scroll inside their own container instead of widening the page on phones.
  function wrapTables(html) { return String(html).replace(/<table\b/gi, '<div class="table-wrap"><table').replace(/<\/table>/gi, '</table></div>'); }
  function ic(name) { return ICONS[name] || ICONS.help || ''; }
  function pad2(n) { n = Number(n); return isFinite(n) ? (n < 10 ? '0' + n : String(n)) : ''; }
  function clamp(n, a, b) { return Math.max(a, Math.min(b, n)); }
  function plural(n, one, few, many) {
    var m10 = n % 10, m100 = n % 100;
    if (m10 === 1 && m100 !== 11) return one;
    if (m10 >= 2 && m10 <= 4 && (m100 < 12 || m100 > 14)) return few;
    return many;
  }
  function qs(sel, root) { return (root || document).querySelector(sel); }
  function qsa(sel, root) { return Array.prototype.slice.call((root || document).querySelectorAll(sel)); }
  function arr(v) { return Array.isArray(v) ? v : []; }
  function str(v) { return v == null ? '' : String(v); }
  function isObj(v) { return !!v && typeof v === 'object'; }
  /* ---------- course data ---------- */
  var RAW = window.CLI_COURSE || {};
  var modules = [];
  var seenModules = {};
  arr(RAW.modules).forEach(function (m) {
    if (!isObj(m) || typeof m.id !== 'string' || seenModules[m.id]) return;
    seenModules[m.id] = true;
    modules.push({
      id: m.id,
      order: isFinite(Number(m.order)) ? Number(m.order) : 999,
      title: str(m.title) || m.id,
      subtitle: str(m.subtitle),
      icon: str(m.icon) || 'school',
      goal: str(m.goal),
      lessons: arr(m.lessons).filter(function (l) { return l && typeof l.id === 'string'; })
    });
  });
  modules.sort(function (a, b) { return (a.order - b.order) || a.id.localeCompare(b.id); });

  var lessons = [];
  var byId = {};
  modules.forEach(function (m) {
    m.lessons = m.lessons.filter(function (l) { return !byId[l.id]; }).map(function (l, k) {
      var entry = {
        lesson: {
          id: l.id,
          title: str(l.title) || l.id,
          minutes: Number(l.minutes) || 0,
          steps: arr(l.steps).filter(isObj),
          glossary: arr(l.glossary),
          quiz: validQuestions(l.quiz)
        },
        module: m,
        index: lessons.length,
        indexInModule: k
      };
      lessons.push(entry);
      byId[l.id] = entry;
      return entry;
    });
  });

  var exam = null;
  if (isObj(RAW.exam)) {
    exam = {
      id: str(RAW.exam.id) || 'exam',
      title: str(RAW.exam.title) || 'Фінальний іспит',
      passPercent: isFinite(Number(RAW.exam.passPercent)) ? Number(RAW.exam.passPercent) : 80,
      quiz: validQuestions(RAW.exam.quiz)
    };
  }

  function validQuestions(list) {
    return arr(list).filter(function (q) {
      return q && Array.isArray(q.options) && q.options.length >= 2 &&
        Number.isInteger(q.correct) && q.correct >= 0 && q.correct < q.options.length;
    });
  }

  var cheatsheet = null;
  if (isObj(RAW.cheatsheet)) {
    cheatsheet = arr(RAW.cheatsheet.sections).filter(function (s) { return s && Array.isArray(s.rows); });
  }

  function shuffledOrder(n) {
    var idx = [];
    for (var k = 0; k < n; k++) idx.push(k);
    for (var j = n - 1; j > 0; j--) {
      var r = Math.floor(Math.random() * (j + 1));
      var t = idx[j]; idx[j] = idx[r]; idx[r] = t;
    }
    return idx;
  }
  // Copy of the question with options in random order and `correct` remapped.
  function shuffleQuestion(q) {
    var order = shuffledOrder(q.options.length);
    return {
      title: q.title, question: q.question, feedback: q.feedback,
      options: order.map(function (i) { return q.options[i]; }),
      correct: order.indexOf(q.correct)
    };
  }

  /* ---------- progress (localStorage, safe) ---------- */
  var storageOk = (function () {
    try {
      var t = '__cli_test__';
      window.localStorage.setItem(t, '1');
      window.localStorage.removeItem(t);
      return true;
    } catch (e) { return false; }
  })();

  function defaults() {
    return { version: 1, unlockAll: false, lessons: {}, exam: { best: 0, attempts: 0, passed: false }, last: null };
  }
  function loadProgress() {
    var d = defaults();
    if (!storageOk) return d;
    try {
      var raw = window.localStorage.getItem(STORAGE_KEY);
      if (!raw) return d;
      var p = JSON.parse(raw);
      if (!isObj(p)) return d;
      d.unlockAll = p.unlockAll === true;
      d.last = typeof p.last === 'string' ? p.last : null;
      if (isObj(p.lessons)) {
        Object.keys(p.lessons).forEach(function (id) {
          var l = p.lessons[id] || {};
          d.lessons[id] = {
            step: Math.max(0, parseInt(l.step, 10) || 0),
            stepsDone: l.stepsDone === true,
            best: clamp(Number(l.best) || 0, 0, 100),
            attempts: Math.max(0, parseInt(l.attempts, 10) || 0),
            passed: l.passed === true
          };
        });
      }
      if (isObj(p.exam)) {
        d.exam = {
          best: clamp(Number(p.exam.best) || 0, 0, 100),
          attempts: Math.max(0, parseInt(p.exam.attempts, 10) || 0),
          passed: p.exam.passed === true
        };
      }
    } catch (e) { /* corrupted or blocked storage: start fresh */ }
    return d;
  }
  var P = loadProgress();
  function save() {
    if (!storageOk) return;
    try { window.localStorage.setItem(STORAGE_KEY, JSON.stringify(P)); } catch (e) { storageOk = false; }
  }
  var EMPTY_LP = { step: 0, stepsDone: false, best: 0, attempts: 0, passed: false };
  function peek(id) { return P.lessons[id] || EMPTY_LP; }
  function lp(id) {
    if (!P.lessons[id]) P.lessons[id] = { step: 0, stepsDone: false, best: 0, attempts: 0, passed: false };
    return P.lessons[id];
  }

  // Session-only state (check, terminal, sim steps) — not persisted.
  var session = {};

  function isUnlocked(entry) {
    if (P.unlockAll || entry.index === 0) return true;
    return !!peek(lessons[entry.index - 1].lesson.id).passed;
  }
  function passedCount() { return lessons.filter(function (e) { return peek(e.lesson.id).passed; }).length; }
  function allPassed() { return lessons.length > 0 && passedCount() === lessons.length; }
  function examUnlocked() { return P.unlockAll || allPassed(); }
  function lessonPercent(entry) {
    var id = entry.lesson.id, p = peek(id);
    if (p.passed) return 100;
    if (p.stepsDone) return 50;
    if (!P.lessons[id]) return 0;
    var n = entry.lesson.steps.length || 1;
    return Math.round(Math.min(1, (p.step + 1) / n) * 50);
  }
  function modulePercent(m) {
    if (!m.lessons.length) return 0;
    var sum = m.lessons.reduce(function (s, e) { return s + lessonPercent(e); }, 0);
    return Math.round(sum / m.lessons.length);
  }
  function moduleMinutes(m) {
    return m.lessons.reduce(function (s, e) { return s + (e.lesson.minutes || 0); }, 0);
  }
  function moduleLabel(m) { return 'Модуль ' + pad2(m.order); }
  function moduleHref(m) { return '#/module/' + encodeURIComponent(m.id); }
  function lessonHref(entry, step) { return '#/lesson/' + encodeURIComponent(entry.lesson.id) + '/' + (step || 1); }
  function quizHref(entry) { return '#/quiz/' + encodeURIComponent(entry.lesson.id); }
  function moduleById(id) { return modules.filter(function (m) { return m.id === id; })[0] || null; }

  function continueTarget() {
    if (!lessons.length) return null;
    var e = P.last && byId[P.last];
    if (e && isUnlocked(e) && !peek(e.lesson.id).passed) {
      var pl = peek(e.lesson.id);
      return {
        href: pl.stepsDone ? quizHref(e) : lessonHref(e, pl.step + 1),
        label: 'Продовжити навчання', sub: e.lesson.title
      };
    }
    for (var i = 0; i < lessons.length; i++) {
      var x = lessons[i];
      if (!peek(x.lesson.id).passed && isUnlocked(x)) {
        var started = !!P.lessons[x.lesson.id];
        return {
          href: lessonHref(x, started ? peek(x.lesson.id).step + 1 : 1),
          label: started || passedCount() ? 'Продовжити навчання' : 'Почати навчання', sub: x.lesson.title
        };
      }
    }
    if (exam && exam.quiz.length && examUnlocked() && !P.exam.passed) {
      return { href: '#/exam', label: 'Скласти іспит', sub: exam.title };
    }
    return { href: '#/modules', label: 'Повторити модулі', sub: 'Курс пройдено' };
  }
  /* ---------- DOM shell ---------- */
  var main = qs('#main');
  var menu = qs('#app-menu');
  var menuButton = qs('#menu-button');
  var unlockToggle = qs('#unlock-toggle');
  var resetDialog = qs('#reset-dialog');
  var snack = qs('#snackbar');
  var topBar = qs('#top-app-bar');

  function hydrateIcons(root) {
    qsa('[data-icon]', root).forEach(function (el) {
      if (!el.firstElementChild) el.innerHTML = ic(el.getAttribute('data-icon'));
    });
  }

  var snackTimer = null;
  function snackbar(msg) {
    if (!snack) return;
    snack.textContent = msg;
    snack.classList.add('show');
    clearTimeout(snackTimer);
    snackTimer = setTimeout(function () { snack.classList.remove('show'); }, 4000);
  }

  var keys = { next: null, choose: null };
  var cleanups = [];
  function cleanup() {
    var list = cleanups;
    cleanups = [];
    list.forEach(function (fn) { try { fn(); } catch (e) { /* ignore */ } });
    keys.next = null;
    keys.choose = null;
  }
  function later(fn, ms) {
    var t = setTimeout(fn, ms);
    cleanups.push(function () { clearTimeout(t); });
    return t;
  }

  function mount(html, title, cls) {
    qsa('dialog[open]', main).forEach(function (d) { try { d.close(); } catch (e) { /* ignore */ } });
    main.innerHTML = '<div class="page' + (cls ? ' ' + cls : '') + '">' + html + '</div>';
    document.title = (title ? title + ' — ' : '') + COURSE_TITLE;
  }

  function focusEl(el) {
    if (!el) return;
    try { el.focus({ preventScroll: true }); } catch (e) { el.focus(); }
  }

  function circular(pct, opts) {
    opts = opts || {};
    var size = opts.large ? 160 : 48, sw = opts.large ? 10 : 4;
    var r = (size - sw) / 2, c = 2 * Math.PI * r, off = c * (1 - clamp(pct, 0, 100) / 100);
    var done = opts.done != null ? opts.done : pct >= 100;
    return '<span class="circular' + (opts.large ? ' large' : '') + (done ? ' done' : '') + '" role="img" aria-label="' +
      esc(opts.label || ('Прогрес ' + pct + '%')) + '"><svg viewBox="0 0 ' + size + ' ' + size + '" aria-hidden="true">' +
      '<circle class="track" cx="' + size / 2 + '" cy="' + size / 2 + '" r="' + r + '" fill="none" stroke-width="' + sw + '"/>' +
      '<circle class="bar" cx="' + size / 2 + '" cy="' + size / 2 + '" r="' + r + '" fill="none" stroke-width="' + sw + '"' +
      (pct > 0 ? ' stroke-linecap="round"' : '') + ' stroke-dasharray="' + c.toFixed(2) + '" stroke-dashoffset="' + off.toFixed(2) + '"/>' +
      '</svg><span class="circular-label" aria-hidden="true">' + pct + '%</span></span>';
  }
  function linear(value, max, label) {
    var pct = max ? clamp(value / max * 100, 0, 100) : 0;
    return '<div class="linear-progress" role="progressbar" aria-label="' + esc(label) + '" aria-valuemin="0" aria-valuemax="' + max +
      '" aria-valuenow="' + value + '"><span style="width:' + pct.toFixed(1) + '%"></span></div>';
  }
  function chip(text, cls, iconName) {
    return '<span class="chip' + (cls ? ' ' + cls : '') + '">' + (iconName ? ic(iconName) : '') + '<span>' + text + '</span></span>';
  }
  function backLink(href, label) {
    return '<a class="btn btn-text back-link" href="' + href + '">' + ic('arrow_back') + '<span>' + esc(label) + '</span></a>';
  }
  function emptyState(iconName, title, text, actions) {
    return '<section class="empty-state"><div class="empty-icon">' + ic(iconName) + '</div>' +
      '<h1 class="headline-small" tabindex="-1">' + esc(title) + '</h1><p class="muted">' + text + '</p>' +
      (actions ? '<div class="actions">' + actions + '</div>' : '') + '</section>';
  }
  function fab(ct) {
    if (!ct) return '';
    return '<a class="fab" href="' + ct.href + '" aria-label="' + esc(ct.label + ': ' + ct.sub) + '">' + ic('play') + '<span>' + esc(ct.label) + '</span></a>';
  }

  /* ---------- risk ---------- */
  var RISK = {
    low: ['chip-success', 'shield', 'Низький ризик', 'Лише читає або показує інформацію.'],
    medium: ['chip-warning', 'warning', 'Середній ризик', 'Змінює файли чи налаштування, але це можна відкотити.'],
    high: ['chip-error', 'danger', 'Високий ризик', 'Може незворотно видалити дані, зламати систему або доступ.']
  };
  function riskChip(r) {
    var x = RISK[r];
    if (!x) return '';
    return '<span class="chip risk ' + x[0] + '" title="' + esc(x[3]) + '">' + ic(x[1]) + '<span>' + x[2] + '</span></span>';
  }

  /* ---------- views ---------- */
  var SKILLS = arr(CFG.skills).filter(function (s) { return Array.isArray(s) && s.length >= 2; });

  function moduleCard(m) {
    var pct = modulePercent(m);
    var first = m.lessons[0];
    var locked = first && !isUnlocked(first);
    var mins = moduleMinutes(m);
    return '<a class="card card-elevated module-card" href="' + moduleHref(m) + '">' +
      '<div class="mc-head"><span class="mc-icon">' + ic(ICONS[m.icon] ? m.icon : 'school') + '</span>' +
      circular(pct, { label: moduleLabel(m) + ': пройдено ' + pct + '%' }) + '</div>' +
      '<div><span class="overline">' + esc(moduleLabel(m)) + '</span><h3 class="title-large">' + esc(m.title) + '</h3></div>' +
      (m.subtitle ? '<p class="body-medium muted">' + esc(m.subtitle) + '</p>' : '') +
      '<div class="mc-foot label-medium">' + (locked ? ic('lock') + '<span>Замкнено · </span>' : ic('book')) +
      '<span>' + m.lessons.length + ' ' + plural(m.lessons.length, 'урок', 'уроки', 'уроків') + (mins ? ' · ~' + mins + ' хв' : '') + '</span></div></a>';
  }

  function examCard() {
    if (!exam) return '';
    var unlocked = examUnlocked();
    return '<a class="card card-elevated module-card exam" href="#/exam">' +
      '<div class="mc-head"><span class="mc-icon">' + ic('emoji_events') + '</span>' +
      circular(P.exam.best, { done: P.exam.passed, label: 'Найкращий результат іспиту ' + P.exam.best + '%' }) + '</div>' +
      '<div><span class="overline">Фінал</span><h3 class="title-large">' + esc(exam.title) + '</h3></div>' +
      '<p class="body-medium muted">' + exam.quiz.length + ' ' + plural(exam.quiz.length, 'питання', 'питання', 'питань') + ' по всьому курсу · прохідний бал ' + exam.passPercent + '%</p>' +
      '<div class="mc-foot label-medium">' + (unlocked ? ic('lock_open') + '<span>Доступний</span>' : ic('lock') + '<span>Після всіх уроків</span>') + '</div></a>';
  }

  function noModulesState() {
    return emptyState('school', 'Уроки ще готуються',
      'Файли модулів не завантажилися. Переконайся, що папка <code>lessons</code> лежить поруч з <code>index.html</code>, і онови сторінку.',
      (CFG.sandbox ? '<a class="btn btn-outlined" href="#/sandbox">' + ic('sandbox') + '<span>Пісочниця</span></a>' : '') + '<a class="btn btn-text" href="#/about">Про курс</a>');
  }

  function viewHome() {
    var ct = continueTarget();
    var html =
      '<section class="hero hero-course" aria-labelledby="hero-title">' +
      '<div class="hero-text">' + (CFG.overline ? '<span class="overline">' + esc(CFG.overline) + '</span>' : '') +
      '<h1 id="hero-title" class="display-small" tabindex="-1">' + esc(COURSE_TITLE) + '</h1>' +
      (CFG.subtitle ? '<p class="body-large muted">' + rt(CFG.subtitle) + '</p>' : '') +
      '<div class="chips">' +
      (modules.length ? chip(modules.length + ' ' + plural(modules.length, 'модуль', 'модулі', 'модулів'), 'chip-primary', 'school') +
        chip(lessons.length + ' ' + plural(lessons.length, 'урок', 'уроки', 'уроків'), '', 'book') : '') +
      chip('Практика в кожному уроці', '', 'terminal') + chip('Працює офлайн', '', 'check') + '</div>' +
      '<div class="actions">' + (ct ? '<a class="btn btn-filled btn-lg" href="' + ct.href + '">' + ic('play') + '<span>' + esc(ct.label) + '</span></a>' : '') +
      (CFG.sandbox ? '<a class="btn btn-outlined btn-lg" href="#/sandbox">' + ic('sandbox') + '<span>Пісочниця</span></a>' : '') +
      (cheatsheet ? '<a class="btn btn-text btn-lg" href="#/cheatsheet">' + ic('description') + '<span>Шпаргалка</span></a>' : '') + '</div></div>' +
      '<div class="hero-term" aria-hidden="true"><div class="term-bar"><i></i><i></i><i></i><span>' + esc(CFG.termTitle || 'terminal') + '</span></div>' +
      '<pre class="term-screen">' + esc(PROMPT) + ' <span class="cursor"></span></pre></div>' +
      '</section>' +

      (SKILLS.length ? '<section class="section" aria-labelledby="skills-title"><div class="section-head"><div><h2 id="skills-title" class="headline-small">Що ти вмітимеш</h2>' +
        '<p class="muted">Без досвіду на старті.</p></div></div><ul class="skills">' +
        SKILLS.map(function (s) { return '<li><span class="skill-icon">' + ic(ICONS[s[0]] ? s[0] : 'check') + '</span><span class="body-medium">' + rt(s[1]) + '</span></li>'; }).join('') +
        '</ul></section>' : '') +

      (CFG.sandbox ? '<section class="section" aria-labelledby="sandbox-title"><a class="card card-outlined sandbox-teaser" href="#/sandbox">' +
        '<span class="st-icon">' + ic('sandbox') + '</span><span class="st-body"><span id="sandbox-title" class="title-large">Пісочниця</span>' +
        '<span class="body-medium muted">Вільний тренажер: вводь команди скільки завгодно — це імітація, справжня система нічого не відчує.</span></span>' +
        '<span class="st-arrow">' + ic('arrow_forward') + '</span></a></section>' : '') +

      '<section class="section" aria-labelledby="modules-title"><div class="section-head"><div><h2 id="modules-title" class="headline-small">Модулі</h2>' +
      (lessons.length ? '<p class="muted">Пройдено ' + passedCount() + ' з ' + lessons.length + ' ' + plural(lessons.length, 'уроку', 'уроків', 'уроків') + '</p>' : '') +
      '</div>' + (modules.length ? '<a class="btn btn-text" href="#/modules">Усі модулі' + ic('arrow_forward') + '</a>' : '') + '</div>' +
      (modules.length ? '<div class="module-grid">' + modules.map(moduleCard).join('') + examCard() + '</div>' : noModulesState()) +
      '</section>' + (modules.length ? fab(ct) : '');
    mount(html, '');
    return qs('#hero-title');
  }

  function viewModules() {
    var html = '<header class="page-head"><span class="ph-icon">' + ic('school') + '</span><div>' +
      '<h1 class="headline-medium" tabindex="-1">Модулі курсу</h1>' +
      '<p class="muted">' + (lessons.length ? 'Пройдено ' + passedCount() + ' з ' + lessons.length + ' ' + plural(lessons.length, 'уроку', 'уроків', 'уроків') + '. Уроки відкриваються по черзі.' : 'Модулі курсу по черзі: від основ до впевненої роботи.') + '</p></div></header>' +
      (lessons.length ? linear(passedCount(), lessons.length, 'Прогрес курсу') : '') +
      '<div class="section" style="margin-top:24px">' +
      (modules.length ? '<div class="module-grid">' + modules.map(moduleCard).join('') + examCard() + '</div>' : noModulesState()) + '</div>' +
      (modules.length ? fab(continueTarget()) : '');
    mount(html, 'Модулі');
    return qs('h1');
  }

  function viewModule(id) {
    var mi = -1;
    modules.forEach(function (m, i) { if (m.id === id) mi = i; });
    if (mi < 0) return viewNotFound('Модуль не знайдено', 'Можливо, файл цього модуля ще не готовий.');
    var m = modules[mi];
    var pct = modulePercent(m);
    var list = m.lessons.map(function (e, k) {
      var L = e.lesson, p = peek(L.id), unlocked = isUnlocked(e), started = !!P.lessons[L.id];
      var cls = p.passed ? ' passed' : (!unlocked ? ' locked' : '');
      var num = p.passed ? ic('check') : (!unlocked ? ic('lock') : String(k + 1));
      var status = p.passed ? chip('Пройдено · ' + p.best + '%', 'chip-success', 'check')
        : !unlocked ? chip('Замкнено', '', 'lock')
          : p.stepsDone ? chip('Залишився quiz', 'chip-primary', 'quiz')
            : started ? chip('В процесі', 'chip-primary', 'play') : '';
      var actions = '';
      if (unlocked) {
        var label = p.passed ? 'Повторити' : started ? 'Продовжити' : 'Почати';
        var href = p.passed ? lessonHref(e, 1) : lessonHref(e, started ? p.step + 1 : 1);
        actions = '<a class="btn ' + (p.passed ? 'btn-tonal' : 'btn-filled') + '" href="' + href + '">' + ic(p.passed ? 'restart' : 'play') + '<span>' + label + '</span></a>';
        if (L.quiz.length && (p.stepsDone || p.passed || P.unlockAll)) {
          actions += '<a class="btn btn-outlined" href="' + quizHref(e) + '">' + ic('quiz') + '<span>Quiz</span></a>';
        }
      }
      return '<div class="card card-outlined lesson-item' + cls + '"><span class="li-num" aria-hidden="true">' + num + '</span>' +
        '<div class="li-body"><span class="overline">Урок ' + (k + 1) + '</span><h3 class="title-medium">' + esc(L.title) + '</h3><div class="chips">' +
        (L.minutes ? chip(L.minutes + ' хв', '', 'timer') : '') + chip(L.steps.length + ' ' + plural(L.steps.length, 'крок', 'кроки', 'кроків'), '', 'list') + status + '</div>' +
        (!unlocked ? '<p class="body-medium muted" style="margin:8px 0 0">Пройди попередній урок, щоб відкрити цей.</p>' : '') +
        '</div><div class="li-actions">' + actions + '</div></div>';
    }).join('');
    var prev = modules[mi - 1], next = modules[mi + 1];
    var html = backLink('#/modules', 'Усі модулі') +
      '<header class="page-head"><span class="ph-icon">' + ic(ICONS[m.icon] ? m.icon : 'school') + '</span><div style="min-width:0;flex:1">' +
      '<span class="overline">' + esc(moduleLabel(m)) + '</span><h1 class="headline-medium" tabindex="-1">' + esc(m.title) + '</h1>' +
      (m.subtitle ? '<p class="muted">' + esc(m.subtitle) + '</p>' : '') + '</div>' + circular(pct, { label: 'Модуль пройдено на ' + pct + '%' }) + '</header>' +
      (m.goal ? '<div class="card goal-card">' + ic('flag') + '<div><div class="title-medium">Мета модуля</div><p class="body-medium" style="margin:4px 0 0">' + esc(m.goal) + '</p></div></div>' : '') +
      '<section class="section" style="margin-top:24px" aria-label="Уроки модуля"><h2 class="title-large">Уроки</h2><div class="lesson-list">' +
      (list || '<p class="muted">У цьому модулі ще немає уроків.</p>') + '</div></section>' +
      '<nav class="module-pager" aria-label="Інші модулі">' +
      (prev ? '<a class="btn btn-outlined" href="' + moduleHref(prev) + '">' + ic('arrow_back') + '<span>' + esc(moduleLabel(prev)) + '</span></a>' : '<span></span>') +
      (next ? '<a class="btn btn-outlined" href="' + moduleHref(next) + '"><span>' + esc(moduleLabel(next)) + '</span>' + ic('arrow_forward') + '</a>'
        : (exam ? '<a class="btn btn-outlined" href="#/exam"><span>Фінальний іспит</span>' + ic('arrow_forward') + '</a>' : '')) +
      '</nav>';
    mount(html, m.title);
    return qs('h1');
  }

  function lockedLessonView(e) {
    var prev = lessons[e.index - 1];
    var html = backLink(moduleHref(e.module), moduleLabel(e.module)) +
      emptyState('lock', 'Урок «' + e.lesson.title + '» ще замкнено',
        'Пройди попередній урок «' + esc(prev ? prev.lesson.title : '') + '» (quiz від ' + LESSON_PASS + '%), щоб відкрити цей. Досвідчені можуть увімкнути «Відкрити всі уроки» в налаштуваннях.',
        (prev ? '<a class="btn btn-filled" href="' + lessonHref(prev, 1) + '">' + ic('play') + '<span>До попереднього уроку</span></a>' : '') +
        '<button class="btn btn-outlined" type="button" data-open-menu>' + ic('settings') + '<span>Налаштування</span></button>');
    mount(html, 'Урок замкнено');
    bindOpenMenu();
    return qs('h1');
  }

  function viewNotFound(title, text) {
    mount(emptyState('help', title || 'Сторінку не знайдено', esc(text || 'Такої адреси в курсі немає.'),
      '<a class="btn btn-filled" href="#/">' + ic('home') + '<span>На головну</span></a>'), title || 'Не знайдено');
    return qs('h1');
  }
  /* ---------- step renderers ---------- */
  var STEP_LABEL = {
    story: ['book', 'Історія', 'chip-secondary'],
    concept: ['lightbulb', 'Поняття', 'chip-secondary'],
    cli: ['terminal', 'Команди', 'chip-secondary'],
    terminal: ['terminal', 'Спробуй сам', 'chip-primary'],
    check: ['quiz', 'Перевір себе', 'chip-primary'],
    summary: ['check_circle', 'Підсумок', 'chip-success']
  };
  var CALLOUT = { tip: ['lightbulb', 'Порада'], warning: ['warning', 'Увага'], danger: ['danger', 'Небезпечно'] };

  function kicker(type, extra) {
    var s = STEP_LABEL[type] || ['help', 'Крок', ''];
    return '<div class="step-kicker">' + chip(s[1], s[2], s[0]) + (extra || '') + '</div>';
  }
  function stepTitle(t) { return '<h2 class="headline-small" id="step-title" tabindex="-1">' + esc(t) + '</h2>'; }
  function body(b) { return b ? '<div class="rt body-large">' + wrapTables(b) + '</div>' : ''; }

  function optionsHtml(options) {
    return '<ul class="options" role="list">' + options.map(function (o, i) {
      return '<li><button class="option" type="button" data-opt="' + i + '"><span class="radio" aria-hidden="true"></span>' +
        '<span class="opt-num" aria-hidden="true">' + (i + 1) + '</span><span class="opt-text">' + rt(o) + '</span>' +
        '<span class="opt-state" aria-hidden="true"></span></button></li>';
    }).join('') + '</ul>';
  }
  function applyAnswer(root, correct, chosen) {
    qsa('.option', root).forEach(function (b, i) {
      b.disabled = true;
      if (i === chosen) b.classList.add('selected');
      if (i === correct) {
        b.classList.add('is-correct');
        qs('.opt-state', b).innerHTML = ic('check');
        b.setAttribute('aria-label', (i === chosen ? 'Твоя відповідь, правильна: ' : 'Правильна відповідь: ') + b.textContent.replace(/^\d/, ''));
      } else if (i === chosen) {
        b.classList.add('is-wrong');
        qs('.opt-state', b).innerHTML = ic('close');
        b.setAttribute('aria-label', 'Твоя відповідь, неправильна: ' + b.textContent.replace(/^\d/, ''));
      } else {
        b.classList.add('dimmed');
      }
    });
  }
  function feedbackHtml(ok, feedback, correctText) {
    return '<div class="feedback-card ' + (ok ? 'ok' : 'bad') + '">' + ic(ok ? 'check_circle' : 'cancel') + '<div>' +
      '<strong>' + (ok ? 'Правильно!' : 'Неправильно') + '</strong>' +
      (!ok && correctText ? '<p>Правильна відповідь: «' + rt(correctText) + '».</p>' : '') +
      (feedback ? '<p>' + rt(feedback) + '</p>' : '') + '</div></div>';
  }

  // Full-string comparison only: trims, collapses spaces, unifies quotes; lowercases for case-insensitive shells.
  function normCmd(s, ci) {
    s = String(s || '').replace(/[“”„«»]/g, '"').replace(/[‘’ʼ]/g, "'").replace(/\s+/g, ' ').trim();
    return (ci == null ? CASE_INSENSITIVE : ci) ? s.toLowerCase() : s;
  }

  function copyText(text) {
    var done = function () { snackbar('Команду скопійовано'); };
    var fallback = function () {
      try {
        var ta = document.createElement('textarea');
        ta.value = text; ta.setAttribute('readonly', ''); ta.style.position = 'fixed'; ta.style.opacity = '0';
        document.body.appendChild(ta); ta.select();
        var ok = document.execCommand('copy');
        document.body.removeChild(ta);
        if (ok) done(); else snackbar('Не вдалося скопіювати — виділи команду вручну');
      } catch (e) { snackbar('Не вдалося скопіювати — виділи команду вручну'); }
    };
    if (navigator.clipboard && window.isSecureContext) navigator.clipboard.writeText(text).then(done, fallback);
    else fallback();
  }


  function placeholderCard(iconName, title, text, extra) {
    return '<div class="wb-placeholder" role="note"><span class="wp-icon">' + ic(iconName) + '</span><div class="wp-body">' +
      '<div class="title-medium">' + esc(title) + '</div><p class="body-medium muted">' + text + '</p>' + (extra || '') + '</div></div>';
  }
  var STEPS = {
    story: function (s) { return { html: kicker('story') + stepTitle(s.title) + body(s.body) }; },

    concept: function (s) {
      return {
        html: kicker('concept') + stepTitle(s.title) + body(s.body) +
          (s.analogy ? '<aside class="analogy" aria-label="Аналогія">' + ic('lightbulb') + '<div><div class="title-medium">Аналогія з життя</div><div class="rt body-large">' + rt(s.analogy) + '</div></div></aside>' : '')
      };
    },

    cli: function (s) {
      var cmds = arr(s.commands).filter(function (c) { return c && c.cmd; });
      var hasHigh = cmds.some(function (c) { return c.risk === 'high'; });
      return {
        html: kicker('cli', hasHigh ? chip('Є небезпечні команди', 'chip-error', 'warning') : '') + stepTitle(s.title) +
          (s.intro ? '<div class="rt body-large" style="margin:0 0 16px">' + rich(s.intro) + '</div>' : '') +
          '<div class="cmd-list">' + cmds.map(function (c, k) {
            return '<div class="cmd' + (c.risk === 'high' ? ' cmd-high' : '') + '"><div class="cmd-line"><pre><code>' + esc(c.cmd) + '</code></pre>' +
              '<button class="icon-btn" type="button" data-copy="' + k + '" aria-label="Копіювати команду" title="Копіювати">' + ic('content_copy') + '</button></div>' +
              '<div class="cmd-meta">' + riskChip(c.risk) + '</div>' +
              (c.explain ? '<div class="explain">' + rich(c.explain) + '</div>' : '') +
              (c.output ? '<div class="output-label label-medium muted">Приклад виводу</div><pre class="output">' + esc(c.output) + '</pre>' : '') + '</div>';
          }).join('') + '</div>',
        bind: function (root) {
          qsa('[data-copy]', root).forEach(function (b) {
            b.addEventListener('click', function () { copyText(String(cmds[Number(b.getAttribute('data-copy'))].cmd)); });
          });
        }
      };
    },

    terminal: function (s, ctx) {
      var expected = arr(s.expected).map(String).filter(Boolean);
      var st = session[ctx.key] || (session[ctx.key] = { attempts: 0, solved: false, revealed: false, lines: [] });
      return {
        html: kicker('terminal') + stepTitle(s.title) +
          '<div class="rt body-large" style="margin:0">' + rich(s.task) + '</div>' +
          '<div class="terminal"><div class="term-bar" aria-hidden="true"><i></i><i></i><i></i><span>' + esc(CFG.termTitle || 'навчальний термінал') + '</span></div>' +
          '<div class="term-screen"><pre class="term-log"></pre>' +
          '<form class="term-form" autocomplete="off"><label class="term-prompt" for="term-input">' + esc(s.prompt || PROMPT) + '</label>' +
          '<input class="term-input" id="term-input" type="text" autocomplete="off" autocapitalize="off" autocorrect="off" spellcheck="false" enterkeyhint="send" aria-describedby="term-feedback">' +
          '<button class="btn" type="submit">' + ic('keyboard_return') + '<span>Виконати</span></button></form></div></div>' +
          '<div class="term-feedback" id="term-feedback" aria-live="polite"></div>',
        bind: function (root) {
          var log = qs('.term-log', root), form = qs('.term-form', root), input = qs('.term-input', root);
          var fb = qs('.term-feedback', root);
          var addLine = function (cls, text) {
            var span = document.createElement('span');
            span.className = cls;
            span.textContent = text + '\n';
            log.appendChild(span);
            log.scrollTop = log.scrollHeight;
          };
          var printOutput = function (text, instant) {
            var lines = String(text || '').split('\n');
            if (instant || reducedMotion) { lines.forEach(function (l) { addLine('t-out', l); }); return; }
            var k = 0;
            var tick = function () {
              if (!log.isConnected || k >= lines.length) return;
              addLine('t-out', lines[k++]);
              later(tick, 45);
            };
            tick();
          };
          var finish = function () {
            input.disabled = true;
            qs('button', form).disabled = true;
            fb.innerHTML = st.revealed
              ? '<div class="feedback-card neutral">' + ic('info') + '<div><strong>Правильна команда</strong><p><code>' + esc(expected[0] || '') + '</code></p>' +
                (s.explain ? '<p>' + rt(s.explain) + '</p>' : '') + '</div></div>'
              : '<div class="feedback-card ok">' + ic('check_circle') + '<div><strong>Правильно! Команда виконана.</strong>' +
                (s.explain ? '<p>' + rt(s.explain) + '</p>' : '') + '</div></div>';
            ctx.unlock();
          };
          var renderFail = function () {
            var html = '<div class="feedback-card bad">' + ic('cancel') + '<div><strong>Не та команда — спробуй ще раз</strong>' +
              (s.hint ? '<p>Підказка: ' + rt(s.hint) + '</p>' : '') + '</div></div>';
            if (st.attempts >= 2) {
              html += '<div class="actions" style="margin-top:12px"><button class="btn btn-tonal" type="button" data-reveal>' + ic('visibility') + '<span>Показати відповідь</span></button></div>';
            }
            fb.innerHTML = html;
            var rv = qs('[data-reveal]', fb);
            if (rv) rv.addEventListener('click', function () {
              st.revealed = true; st.solved = true;
              var cmd = expected[0] || '';
              st.lines.push(['t-cmd', (s.prompt || PROMPT) + ' ' + cmd], ['t-out', str(s.output)]);
              addLine('t-cmd', (s.prompt || PROMPT) + ' ' + cmd);
              printOutput(s.output);
              finish();
              focusEl(ctx.nextButton());
            });
          };
          st.lines.forEach(function (l) { if (l[0] === 't-out') printOutput(l[1], true); else addLine(l[0], l[1]); });
          if (st.solved) finish();
          else if (st.attempts) renderFail();

          form.addEventListener('submit', function (ev) {
            ev.preventDefault();
            var val = input.value;
            if (!val.trim() || st.solved) return;
            addLine('t-cmd', (s.prompt || PROMPT) + ' ' + val.trim());
            st.lines.push(['t-cmd', (s.prompt || PROMPT) + ' ' + val.trim()]);
            var ci = typeof s.caseInsensitive === 'boolean' ? s.caseInsensitive : null; // per-step override (e.g. Linux inside a PowerShell course)
            var ok = expected.some(function (x) { return normCmd(x, ci) === normCmd(val, ci); });
            input.value = '';
            if (ok) {
              st.solved = true;
              st.lines.push(['t-out', str(s.output)]);
              printOutput(s.output);
              finish();
              focusEl(ctx.nextButton());
            } else {
              st.attempts++;
              addLine('t-err', '# команда не виконує завдання');
              st.lines.push(['t-err', '# команда не виконує завдання']);
              renderFail();
              input.focus();
            }
          });
        }
      };
    },

    check: function (s, ctx) {
      var raw = arr(s.options).map(String);
      var order = session[ctx.key + ':order'] || (session[ctx.key + ':order'] = shuffledOrder(raw.length));
      var options = order.map(function (k) { return raw[k]; });
      var correct = order.indexOf(s.correct);
      return {
        html: kicker('check') + stepTitle(s.title) + '<div class="rt body-large" style="margin:0">' + rich(s.question) + '</div>' +
          optionsHtml(options) + '<div class="feedback-slot" aria-live="polite"></div>',
        bind: function (root) {
          var slot = qs('.feedback-slot', root);
          var show = function (i) {
            applyAnswer(root, correct, i);
            slot.innerHTML = feedbackHtml(i === correct, s.feedback, options[correct]);
          };
          var answer = function (i) {
            if (session[ctx.key] != null) return false;
            if (i < 0 || i >= options.length) return false;
            session[ctx.key] = { choice: i };
            show(i);
            ctx.unlock();
            focusEl(ctx.nextButton());
            return true;
          };
          qsa('.option', root).forEach(function (b) {
            b.addEventListener('click', function () { answer(Number(b.getAttribute('data-opt'))); });
          });
          if (session[ctx.key] && session[ctx.key].choice != null) { show(session[ctx.key].choice); ctx.unlock(); }
          keys.choose = function (i) { return session[ctx.key] == null ? answer(i) : false; };
        }
      };
    },

    callout: function (s) {
      var v = CALLOUT[s.variant] ? s.variant : 'tip';
      return {
        cls: 'callout ' + v,
        html: '<div class="step-kicker">' + chip(CALLOUT[v][1], '', CALLOUT[v][0]) + '</div>' +
          '<div class="co-row"><span class="co-icon">' + ic(CALLOUT[v][0]) + '</span><div class="co-body">' + stepTitle(s.title) + body(s.body) + '</div></div>'
      };
    },

    summary: function (s, ctx) {
      var pts = arr(s.points);
      var nq = ctx.lesson.quiz.length;
      return {
        html: kicker('summary') + stepTitle(s.title) +
          '<ul class="summary-list">' + pts.map(function (p) { return '<li>' + ic('check') + '<span class="body-large">' + rt(p) + '</span></li>'; }).join('') + '</ul>' +
          (nq ? '<p class="summary-next body-medium muted">' + ic('quiz') + '<span>Далі — quiz із ' + nq + ' ' + plural(nq, 'питання', 'питань', 'питань') +
            '. Набери від ' + LESSON_PASS + '%, щоб відкрити наступний урок.</span></p>' : '')
      };
    }
  };

  function renderStep(s, ctx) {
    var fn = STEPS[s.type];
    if (!fn) {
      return { html: kicker('unknown') + stepTitle(s.title || 'Крок') + '<p class="muted">Цей тип кроку («' + esc(s.type) + '») поки не підтримується.</p>' };
    }
    try { return fn(s, ctx); } catch (e) {
      if (window.console) console.warn('Step render failed', s, e);
      return { html: kicker('unknown') + stepTitle(s.title || 'Крок') + '<p class="muted">Не вдалося показати цей крок.</p>' };
    }
  }

  function viewLesson(id, stepStr) {
    var e = byId[id];
    if (!e) return viewNotFound('Урок не знайдено', 'Можливо, файл цього модуля ще не готовий.');
    if (!isUnlocked(e)) return lockedLessonView(e);
    var L = e.lesson, n = L.steps.length;
    if (!n) {
      mount(backLink(moduleHref(e.module), moduleLabel(e.module)) +
        emptyState('book', L.title, 'У цьому уроці ще немає кроків.', L.quiz.length ? '<a class="btn btn-filled" href="' + quizHref(e) + '">' + ic('quiz') + '<span>До quiz</span></a>' : ''), L.title);
      return qs('h1');
    }
    var p = lp(L.id);
    var free = p.stepsDone || p.passed;
    var gatedType = function (k) {
      var step = L.steps[k], t = step && step.type;
      return t === 'check' || t === 'terminal';
    };
    var solved = function (k) {
      var st = session[L.id + ':' + k];
      return !!st && (st.choice != null || st.solved === true);
    };
    var maxAllowed = free ? n - 1 : Math.min(n - 1, (gatedType(p.step) && !solved(p.step)) ? p.step : p.step + 1);
    var i = clamp((parseInt(stepStr, 10) || 1) - 1, 0, n - 1);
    if (i > maxAllowed) {
      i = maxAllowed;
      try { history.replaceState(null, '', lessonHref(e, i + 1)); } catch (err) { /* file:// in some browsers */ }
    }
    p.step = Math.max(p.step, i);
    P.last = L.id;
    save();

    var s = L.steps[i];
    var isLast = i === n - 1;
    var ctx = {
      key: L.id + ':' + i,
      lesson: L,
      unlock: function () {
        var b = qs('#step-next');
        if (b) b.disabled = false;
        var h = qs('#step-hint');
        if (h) h.textContent = 'Enter — далі';
      },
      nextButton: function () { return qs('#step-next'); }
    };
    var r = renderStep(s, ctx);
    var needsAnswer = !free && !r.ungated && gatedType(i) && i === p.step && !solved(i);
    var nextLabel = isLast ? (L.quiz.length ? 'До quiz' : 'Завершити урок') : 'Далі';
    var hint = needsAnswer ? (s.type === 'check' ? 'Обери відповідь, щоб продовжити' : 'Виконай команду, щоб продовжити') : 'Enter — далі';
    var html =
      '<div class="player-head">' + backLink(moduleHref(e.module), moduleLabel(e.module) + ' · ' + e.module.title) +
      '<h1 class="title-large">' + esc(L.title) + '</h1>' +
      linear(i + 1, n, 'Прогрес уроку') +
      '<div class="player-meta"><span class="label-large muted">Крок ' + (i + 1) + ' з ' + n + '</span>' +
      (L.minutes ? chip(L.minutes + ' хв', '', 'timer') : '') + '</div></div>' +
      '<article class="step-card step-' + esc(s.type || 'unknown') + (r.cls ? ' ' + r.cls : '') + '" aria-labelledby="step-title">' + r.html + '</article>' +
      '<div class="player-actions">' +
      (i > 0 ? '<a class="btn btn-outlined" href="' + lessonHref(e, i) + '">' + ic('arrow_back') + '<span>Назад</span></a>'
        : '<a class="btn btn-outlined" href="' + moduleHref(e.module) + '">' + ic('arrow_back') + '<span>Модуль</span></a>') +
      '<span class="hint" id="step-hint" aria-live="polite">' + esc(hint) + '</span>' +
      '<button class="btn btn-filled" type="button" id="step-next"' + (needsAnswer ? ' disabled' : '') + '><span>' + nextLabel + '</span>' + ic(isLast ? 'quiz' : 'arrow_forward') + '</button>' +
      '</div>';
    mount(html, L.title);
    var root = qs('.step-card');
    if (r.bind) {
      try { r.bind(root); } catch (err) { if (window.console) console.warn('Step bind failed', s, err); ctx.unlock(); }
    }

    var goNext = function () {
      var b = qs('#step-next');
      if (!b) return;
      if (b.disabled) {
        snackbar(s.type === 'check' ? 'Спершу обери відповідь' : 'Спершу виконай завдання або покажи відповідь після 2 спроб');
        return;
      }
      if (!isLast) {
        p.step = Math.max(p.step, i + 1);
        save();
        location.hash = lessonHref(e, i + 2);
        return;
      }
      p.stepsDone = true;
      if (L.quiz.length) { save(); location.hash = quizHref(e); return; }
      var was = p.passed;
      p.passed = true;
      save();
      if (!was) snackbar('Урок пройдено!');
      var nx = lessons[e.index + 1];
      location.hash = nx ? lessonHref(nx, 1) : moduleHref(e.module);
    };
    qs('#step-next').addEventListener('click', goNext);
    keys.next = goNext;
    return qs('#step-title');
  }
  /* ---------- quiz engine ---------- */
  function resultComment(pct) {
    if (pct >= 90) return 'Відмінний результат! Ти впевнено розумієш цю тему.';
    if (pct >= 70) return 'Добрий результат. Основне засвоєно — кілька деталей варто ще раз переглянути.';
    if (pct >= 50) return 'Непогано, але варто ще попрактикуватися: переглянь кроки уроку й спробуй ще раз.';
    return 'Рекомендуємо повторити матеріал і пройти quiz ще раз — у тебе все вийде.';
  }

  // opts: { questions, onFinish(score, pct) -> {passed, best, attempts, statusText, actions(html)} }
  function runQuiz(host, opts) {
    var SRC = opts.questions, N = SRC.length, Q = SRC.map(shuffleQuestion);
    var state = { k: 0, score: 0, chosen: null };

    function renderQuestion() {
      var q = Q[state.k];
      state.chosen = null;
      var last = state.k === N - 1;
      host.innerHTML =
        '<div class="quiz-top"><span class="label-large">Питання ' + (state.k + 1) + ' з ' + N + '</span>' +
        '<span class="label-large muted">Правильних: <span id="q-score">' + state.score + '</span></span></div>' +
        linear(state.k, N, 'Прогрес quiz') +
        '<h2 class="title-large" id="q-title" tabindex="-1">' + esc(q.title || ('Питання ' + (state.k + 1))) + '</h2>' +
        '<p class="question">' + rt(q.question) + '</p>' +
        optionsHtml(q.options.map(String)) +
        '<div class="feedback-slot" aria-live="polite"></div>' +
        '<div class="quiz-foot"><button class="btn btn-filled btn-lg" type="button" id="q-next" disabled><span>' +
        (last ? 'Показати результат' : 'Наступне питання') + '</span>' + ic(last ? 'emoji_events' : 'arrow_forward') + '</button></div>';
      qsa('.option', host).forEach(function (b) {
        b.addEventListener('click', function () { choose(Number(b.getAttribute('data-opt'))); });
      });
      qs('#q-next', host).addEventListener('click', next);
      keys.choose = function (i) { return choose(i); };
      keys.next = function () { var b = qs('#q-next', host); if (b && !b.disabled) next(); };
    }

    function choose(i) {
      var q = Q[state.k];
      if (state.chosen != null || i < 0 || i >= q.options.length) return false;
      state.chosen = i;
      var ok = i === q.correct;
      if (ok) state.score++;
      applyAnswer(host, q.correct, i);
      qs('.feedback-slot', host).innerHTML = feedbackHtml(ok, q.feedback, String(q.options[q.correct]));
      qs('#q-score', host).textContent = state.score;
      var bar = qs('.linear-progress', host);
      bar.setAttribute('aria-valuenow', state.k + 1);
      qs('span', bar).style.width = ((state.k + 1) / N * 100).toFixed(1) + '%';
      var nb = qs('#q-next', host);
      nb.disabled = false;
      focusEl(nb);
      return true;
    }

    function next() {
      if (state.chosen == null) return;
      if (state.k < N - 1) {
        state.k++;
        renderQuestion();
        focusEl(qs('#q-title', host));
        if (host.scrollIntoView) host.scrollIntoView({ block: 'start', behavior: reducedMotion ? 'auto' : 'smooth' });
      } else {
        showResult();
      }
    }

    function showResult() {
      keys.choose = null;
      var pct = Math.round(state.score / N * 100);
      var res = opts.onFinish(state.score, pct);
      host.innerHTML = '<div class="result">' +
        circular(pct, { large: true, done: res.passed, label: 'Результат ' + pct + '%' }) +
        '<h2 class="headline-small" id="q-title" tabindex="-1">' + state.score + ' з ' + N + ' правильних</h2>' +
        '<span class="chip ' + (res.passed ? 'chip-success' : 'chip-error') + ' result-status">' + ic(res.passed ? 'check_circle' : 'info') + '<span>' +
        esc(res.statusText) + '</span></span>' +
        '<p class="body-large">' + esc(resultComment(pct)) + '</p>' +
        '<p class="body-medium muted">Найкращий результат: ' + res.best + '% · спроб: ' + res.attempts + '</p>' +
        '<div class="actions">' + res.actions + '</div></div>';
      var retry = qs('[data-retry]', host);
      if (retry) retry.addEventListener('click', function () {
        state.k = 0; state.score = 0;
        Q = SRC.map(shuffleQuestion);
        renderQuestion();
        focusEl(qs('#q-title', host));
      });
      var primary = qs('.result .btn-filled', host);
      keys.next = primary ? function () { primary.click(); } : null;
      focusEl(qs('#q-title', host));
    }

    renderQuestion();
  }

  function viewQuiz(id) {
    var e = byId[id];
    if (!e) return viewNotFound('Quiz не знайдено', 'Можливо, файл цього модуля ще не готовий.');
    if (!isUnlocked(e)) return lockedLessonView(e);
    var L = e.lesson;
    var back = backLink(lessonHref(e, 1), 'Урок: ' + L.title);
    if (!L.quiz.length) {
      mount(back + emptyState('quiz', 'У цьому уроці ще немає quiz', 'Питання для цього уроку ще готуються.'), 'Quiz');
      return qs('h1');
    }
    mount(back +
      '<header class="page-head"><span class="ph-icon">' + ic('quiz') + '</span><div><span class="overline">' + esc(moduleLabel(e.module)) + ' · Quiz уроку</span>' +
      '<h1 class="headline-small">' + esc(L.title) + '</h1><p class="muted">' + L.quiz.length + ' ' + plural(L.quiz.length, 'питання', 'питання', 'питань') +
      ' · одна правильна відповідь · прохідний бал ' + LESSON_PASS + '%</p></div></header>' +
      '<section class="quiz-card" id="quiz-host" aria-label="Quiz"></section>', 'Quiz: ' + L.title);
    var host = qs('#quiz-host');
    runQuiz(host, {
      questions: L.quiz,
      onFinish: function (score, pct) {
        var p = lp(L.id);
        var was = p.passed;
        p.attempts++;
        p.best = Math.max(p.best, pct);
        p.stepsDone = true;
        if (pct >= LESSON_PASS) p.passed = true;
        P.last = L.id;
        save();
        var nx = lessons[e.index + 1];
        if (!was && p.passed) snackbar(nx ? 'Урок пройдено! Відкрито наступний урок.' : 'Урок пройдено!');
        var passedNow = pct >= LESSON_PASS;
        var actions = '';
        if (p.passed && nx) actions += '<a class="btn btn-filled" href="' + lessonHref(nx, 1) + '"><span>Наступний урок</span>' + ic('arrow_forward') + '</a>';
        else if (p.passed && !nx && exam && exam.quiz.length) actions += '<a class="btn btn-filled" href="#/exam">' + ic('emoji_events') + '<span>До іспиту</span></a>';
        actions += '<button class="btn ' + (p.passed ? 'btn-tonal' : 'btn-filled') + '" type="button" data-retry>' + ic('restart') + '<span>Спробувати ще раз</span></button>';
        actions += '<a class="btn btn-outlined" href="' + lessonHref(e, 1) + '">' + ic('book') + '<span>Повторити урок</span></a>';
        actions += '<a class="btn btn-text" href="' + moduleHref(e.module) + '">До модуля</a>';
        return {
          passed: passedNow, best: p.best, attempts: p.attempts, actions: actions,
          statusText: passedNow ? 'Урок пройдено' : (was ? 'Урок уже пройдено раніше, цього разу менше ' + LESSON_PASS + '%' : 'Потрібно щонайменше ' + LESSON_PASS + '%')
        };
      }
    });
    return qs('#q-title');
  }

  function viewExam() {
    if (!exam || !exam.quiz.length) {
      mount(emptyState('emoji_events', 'Іспит ще готується', 'Питання фінального іспиту ще не завантажилися.',
        '<a class="btn btn-outlined" href="#/modules">До модулів</a>'), 'Іспит');
      return qs('h1');
    }
    var N = exam.quiz.length;
    var head = '<header class="page-head"><span class="ph-icon">' + ic('emoji_events') + '</span><div><span class="overline">Фінал курсу</span>' +
      '<h1 class="headline-medium" tabindex="-1">' + esc(exam.title) + '</h1><p class="muted">' + N + ' ' + plural(N, 'питання', 'питання', 'питань') +
      ' по всьому курсу · прохідний бал ' + exam.passPercent + '%</p></div></header>';
    if (!examUnlocked()) {
      var ct = continueTarget();
      mount(backLink('#/modules', 'Модулі') + head +
        emptyState('lock', 'Іспит відкриється після всіх уроків',
          'Пройдено ' + passedCount() + ' з ' + lessons.length + ' ' + plural(lessons.length, 'уроку', 'уроків', 'уроків') + '. Досвідчені можуть увімкнути «Відкрити всі уроки» в налаштуваннях.',
          (ct ? '<a class="btn btn-filled" href="' + ct.href + '">' + ic('play') + '<span>Продовжити навчання</span></a>' : '') +
          '<button class="btn btn-outlined" type="button" data-open-menu>' + ic('settings') + '<span>Налаштування</span></button>'), 'Іспит');
      qs('.empty-state h1').outerHTML = '<h2 class="headline-small">Іспит відкриється після всіх уроків</h2>';
      bindOpenMenu();
      return qs('h1');
    }
    mount(backLink('#/modules', 'Модулі') + head +
      '<section class="quiz-card" id="quiz-host" aria-label="Іспит"><div class="result">' +
      circular(P.exam.best, { large: true, done: P.exam.passed, label: 'Найкращий результат ' + P.exam.best + '%' }) +
      '<h2 class="headline-small">' + (P.exam.passed ? 'Іспит уже складено' : 'Готовий перевірити себе?') + '</h2>' +
      '<p class="body-large">Питання охоплюють усі модулі. Відповідь не можна змінити після вибору — подумай, перш ніж обирати.</p>' +
      '<p class="body-medium muted">Спроб: ' + P.exam.attempts + '</p>' +
      '<div class="actions"><button class="btn btn-filled btn-lg" type="button" id="exam-start">' + ic('play') + '<span>' + (P.exam.attempts ? 'Скласти ще раз' : 'Почати іспит') + '</span></button></div>' +
      '</div></section>', 'Іспит');
    var host = qs('#quiz-host');
    var start = function () {
      runQuiz(host, {
        questions: shuffledOrder(exam.quiz.length).map(function (i) { return exam.quiz[i]; }),
        onFinish: function (score, pct) {
          var was = P.exam.passed;
          P.exam.attempts++;
          P.exam.best = Math.max(P.exam.best, pct);
          if (pct >= exam.passPercent) P.exam.passed = true;
          save();
          var passedNow = pct >= exam.passPercent;
          if (!was && passedNow) snackbar('Іспит складено! Вітаємо з завершенням курсу.');
          return {
            passed: passedNow, best: P.exam.best, attempts: P.exam.attempts,
            statusText: passedNow ? 'Іспит складено' : 'Потрібно щонайменше ' + exam.passPercent + '%',
            actions: '<button class="btn ' + (passedNow ? 'btn-tonal' : 'btn-filled') + '" type="button" data-retry>' + ic('restart') + '<span>Спробувати ще раз</span></button>' +
              '<a class="btn btn-outlined" href="#/modules">' + ic('school') + '<span>Повторити модулі</span></a>' +
              '<a class="btn btn-text" href="#/glossary">Словник</a>'
          };
        }
      });
      focusEl(qs('#q-title', host));
    };
    qs('#exam-start').addEventListener('click', start);
    keys.next = start;
    return qs('h1');
  }

  /* ---------- sandbox (trainer in iframe) ---------- */
  function viewSandbox() {
    var head = '<header class="page-head"><span class="ph-icon">' + ic('sandbox') + '</span><div>' +
      '<h1 class="headline-medium" tabindex="-1">Пісочниця</h1>' +
      '<p class="muted">Вільний тренажер курсу: модулі з командами, підказки українською, режим тестування. Це імітація — справжня система нічого не відчує.</p></div></header>';
    if (!CFG.sandbox) {
      mount(head + emptyState('sandbox', 'У цього курсу немає окремого тренажера', 'Практика вбудована в уроки — кроки «Спробуй сам».',
        '<a class="btn btn-filled" href="#/modules">' + ic('school') + '<span>До модулів</span></a>'), 'Пісочниця');
      qs('.empty-state h1').outerHTML = '<h2 class="headline-small">У цього курсу немає окремого тренажера</h2>';
      return qs('h1');
    }
    var src = String(CFG.sandbox);
    var html = head +
      '<div class="actions sandbox-actions"><a class="btn btn-tonal" href="' + esc(src) + '">' + ic('open_in_new') + '<span>Відкрити на весь екран</span></a></div>' +
      '<div class="sandbox-frame"><iframe src="' + esc(src + (src.indexOf('?') === -1 ? '?' : '&') + 'embed=1') + '" title="Тренажер курсу"></iframe></div>';
    mount(html, 'Пісочниця', 'wide');
    return qs('h1');
  }

  /* ---------- cheatsheet ---------- */
  function viewCheatsheet() {
    var head = '<header class="page-head"><span class="ph-icon">' + ic('description') + '</span><div>' +
      '<h1 class="headline-medium" tabindex="-1">Шпаргалка</h1><p class="muted">Команди курсу з коротким поясненням і рівнем ризику.</p></div></header>';
    if (!cheatsheet || !cheatsheet.length) {
      mount(head + emptyState('description', 'Шпаргалка ще готується', 'Команди з\'являться тут, щойно буде готовий файл шпаргалки.'), 'Шпаргалка');
      qs('.empty-state h1').outerHTML = '<h2 class="headline-small">Шпаргалка ще готується</h2>';
      return qs('h1');
    }
    var html = head +
      '<ul class="risk-legend">' + ['low', 'medium', 'high'].map(function (r) { return '<li>' + riskChip(r) + '<span class="body-medium muted">' + esc(RISK[r][3]) + '</span></li>'; }).join('') + '</ul>' +
      '<label class="search-field" for="cs-search">' + ic('search') + '<span class="visually-hidden">Пошук команди</span>' +
      '<input id="cs-search" type="search" placeholder="Пошук команди або опису…" autocomplete="off" aria-controls="cs-results"></label>' +
      '<p class="body-medium muted" id="cs-count" role="status" style="margin:12px 4px 0"></p><div id="cs-results"></div>';
    mount(html, 'Шпаргалка');
    var input = qs('#cs-search'), out = qs('#cs-results'), count = qs('#cs-count');
    var render = function () {
      var q = input.value.trim().toLocaleLowerCase('uk');
      var total = 0;
      var html2 = cheatsheet.map(function (sec) {
        var rows = sec.rows.filter(function (r) { return r && r.cmd && (!q || (r.cmd + ' ' + (r.desc || '')).toLocaleLowerCase('uk').indexOf(q) !== -1); });
        total += rows.length;
        if (!rows.length) return '';
        return '<section class="card card-outlined cs-section"><h2 class="title-large">' + esc(sec.title) + '</h2><div class="table-wrap"><table class="cs-table">' +
          '<thead><tr><th scope="col">Команда</th><th scope="col">Що робить</th><th scope="col">Ризик</th></tr></thead><tbody>' +
          rows.map(function (r) {
            return '<tr><td><code>' + esc(r.cmd) + '</code></td><td>' + rt(r.desc || '') + '</td><td>' + riskChip(r.risk) + '</td></tr>';
          }).join('') + '</tbody></table></div></section>';
      }).join('');
      count.textContent = q ? ('Знайдено: ' + total) : (total + ' ' + plural(total, 'команда', 'команди', 'команд'));
      out.innerHTML = total ? html2 : '<div class="empty-state" style="margin-top:16px"><div class="empty-icon">' + ic('search') + '</div><p class="muted">Нічого не знайдено за запитом «' + esc(input.value.trim()) + '».</p></div>';
    };
    input.addEventListener('input', render);
    render();
    return qs('h1');
  }

  /* ---------- glossary ---------- */
  function collectGlossary() {
    var map = {};
    var list = [];
    lessons.forEach(function (e) {
      e.lesson.glossary.forEach(function (g) {
        if (!g || !g.term) return;
        var key = String(g.term).trim().toLocaleLowerCase('uk');
        if (!map[key]) { map[key] = { term: String(g.term).trim(), def: str(g.def), refs: [] }; list.push(map[key]); }
        if (!map[key].refs.some(function (r) { return r.entry === e; })) map[key].refs.push({ entry: e });
      });
    });
    return list.sort(function (a, b) { return a.term.localeCompare(b.term, 'uk', { sensitivity: 'base' }); });
  }

  function viewGlossary() {
    var terms = collectGlossary();
    var html = '<header class="page-head"><span class="ph-icon">' + ic('book') + '</span><div>' +
      '<h1 class="headline-medium" tabindex="-1">Словник</h1><p class="muted">Терміни з усіх уроків курсу простими словами.</p></div></header>';
    if (!terms.length) {
      mount(html + emptyState('book', 'Словник поки порожній', 'Терміни з\'являться, коли завантажаться уроки курсу.'), 'Словник');
      qs('.empty-state h1').outerHTML = '<h2 class="headline-small">Словник поки порожній</h2>';
      return qs('h1');
    }
    html += '<label class="search-field" for="gl-search">' + ic('search') + '<span class="visually-hidden">Пошук терміна</span>' +
      '<input id="gl-search" type="search" placeholder="Пошук терміна…" autocomplete="off" aria-controls="gl-results"></label>' +
      '<p class="body-medium muted" id="gl-count" role="status" style="margin:12px 4px 0"></p><div id="gl-results"></div>';
    mount(html, 'Словник');
    var input = qs('#gl-search'), out = qs('#gl-results'), count = qs('#gl-count');
    var render = function () {
      var q = input.value.trim().toLocaleLowerCase('uk');
      var found = terms.filter(function (t) { return !q || (t.term + ' ' + t.def).toLocaleLowerCase('uk').indexOf(q) !== -1; });
      count.textContent = q ? ('Знайдено: ' + found.length) : (terms.length + ' ' + plural(terms.length, 'термін', 'терміни', 'термінів'));
      if (!found.length) {
        out.innerHTML = '<div class="empty-state" style="margin-top:16px"><div class="empty-icon">' + ic('search') + '</div><p class="muted">Нічого не знайдено за запитом «' + esc(input.value.trim()) + '».</p></div>';
        return;
      }
      var letter = '', html2 = '';
      found.forEach(function (t) {
        var l = (t.term.replace(/^[^0-9A-Za-zА-ЯЄІЇҐа-яєіїґ]+/, '') || t.term).charAt(0).toLocaleUpperCase('uk');
        if (l !== letter) { html2 += (letter ? '</div>' : '') + '<h2 class="title-large glossary-letter">' + esc(l) + '</h2><div class="glossary-list">'; letter = l; }
        html2 += '<article class="card card-outlined term-card"><h3 class="title-medium">' + esc(t.term) + '</h3><div class="rt body-medium">' + rt(t.def) + '</div>' +
          '<div class="term-refs">' + t.refs.map(function (r) {
            return '<a href="' + lessonHref(r.entry, 1) + '">' + esc(moduleLabel(r.entry.module) + ' · ' + r.entry.lesson.title) + '</a>';
          }).join('') + '</div></article>';
      });
      out.innerHTML = html2 + '</div>';
    };
    input.addEventListener('input', render);
    render();
    return qs('h1');
  }

  /* ---------- about ---------- */
  function viewAbout() {
    var sources = arr(CFG.sources).filter(function (s) { return s && s.href; });
    var html = '<header class="page-head"><span class="ph-icon">' + ic('info') + '</span><div>' +
      '<h1 class="headline-medium" tabindex="-1">Про курс</h1><p class="muted">' + esc(COURSE_TITLE) + (CFG.overline ? ' · ' + esc(CFG.overline) : '') + '</p></div></header>' +
      '<div class="about-grid">' +
      (SKILLS.length ? '<section class="card"><h2 class="title-large">' + ic('flag') + 'Мета</h2><div class="rt body-medium"><p>Після курсу ти зможеш:</p><ul>' +
        SKILLS.map(function (s) { return '<li>' + rt(s[1]) + '</li>'; }).join('') + '</ul></div></section>' : '') +
      (CFG.audience ? '<section class="card"><h2 class="title-large">' + ic('school') + 'Для кого</h2><div class="rt body-medium">' + CFG.audience + '</div></section>' : '') +
      '<section class="card about-safety"><h2 class="title-large">' + ic('shield') + 'Безпека</h2><div class="rt body-medium">' +
      (CFG.safety || '') +
      '<p>Кожна команда в уроках має рівень ризику:</p><ul class="risk-legend">' + ['low', 'medium', 'high'].map(function (r) { return '<li>' + riskChip(r) + '<span>' + esc(RISK[r][3]) + '</span></li>'; }).join('') + '</ul>' +
      '<p>Кроки «Спробуй сам» і Пісочниця — імітація: введені там команди нічого не виконують на твоєму комп\'ютері.</p></div></section>' +
      '<section class="card"><h2 class="title-large">' + ic('list') + 'Як влаштовано</h2><div class="rt body-medium"><ul>' +
      '<li><strong>Урок</strong> — кроки: пояснення з аналогією, команди, спроба в терміналі, перевірки, підсумок.</li>' +
      '<li><strong>Quiz уроку</strong> — від ' + LESSON_PASS + '% відкриває наступний урок.</li>' +
      (exam ? '<li><strong>Фінальний іспит</strong> — після всіх уроків, прохідний бал ' + exam.passPercent + '%.</li>' : '') +
      '<li><a href="#/glossary">Словник</a>' + (cheatsheet ? ', <a href="#/cheatsheet">шпаргалка</a>' : '') + (CFG.sandbox ? ', <a href="#/sandbox">пісочниця</a>' : '') + (CFG.quizBank ? ', <a href="' + esc(CFG.quizBank) + '">банк питань</a>' : '') + '.</li></ul></div></section>' +
      (sources.length ? '<section class="card"><h2 class="title-large">' + ic('book') + 'Джерела</h2><div class="rt body-medium"><ul>' +
        sources.map(function (s) { return '<li><a href="' + esc(s.href) + '" target="_blank" rel="noopener noreferrer">' + esc(s.label || s.href) + '</a></li>'; }).join('') + '</ul></div></section>' : '') +
      '<section class="card"><h2 class="title-large">' + ic('settings') + 'Прогрес</h2><div class="rt body-medium">' +
      '<p>' + (storageOk ? 'Прогрес зберігається лише в цьому браузері (localStorage, ключ <code>' + esc(STORAGE_KEY) + '</code>). Курс працює офлайн і нічого не надсилає в інтернет.'
        : 'Сховище браузера недоступне — прогрес діятиме лише до закриття сторінки.') + '</p></div>' +
      '<div class="actions" style="margin-top:12px"><button class="btn btn-outlined" type="button" data-open-reset>' + ic('restart') + '<span>Скинути прогрес</span></button></div></section>' +
      '</div>';
    mount(html, 'Про курс');
    qsa('[data-open-reset]').forEach(function (b) { b.addEventListener('click', openReset); });
    return qs('h1');
  }

  /* ---------- menu, dialog ---------- */
  function syncUnlock() { unlockToggle.setAttribute('aria-checked', String(P.unlockAll)); }
  function openMenu() {
    syncUnlock();
    menu.hidden = false;
    menuButton.setAttribute('aria-expanded', 'true');
    focusEl(qs('.menu-item', menu));
  }
  function closeMenu(returnFocus) {
    if (menu.hidden) return;
    menu.hidden = true;
    menuButton.setAttribute('aria-expanded', 'false');
    if (returnFocus) focusEl(menuButton);
  }
  function bindOpenMenu() {
    qsa('[data-open-menu]').forEach(function (b) {
      b.addEventListener('click', function (ev) { ev.stopPropagation(); openMenu(); });
    });
  }
  function openReset() {
    closeMenu(false);
    if (resetDialog && typeof resetDialog.showModal === 'function') resetDialog.showModal();
    else if (window.confirm('Скинути весь прогрес курсу?')) doReset();
  }
  function doReset() {
    P = defaults();
    session = {};
    save();
    if (storageOk) { try { window.localStorage.removeItem(STORAGE_KEY); } catch (e) { /* ignore */ } }
    syncUnlock();
    snackbar('Прогрес скинуто');
    if (location.hash && location.hash !== '#/') location.hash = '#/';
    else render();
  }

  menuButton.addEventListener('click', function (ev) {
    ev.stopPropagation();
    if (menu.hidden) openMenu(); else closeMenu(true);
  });
  document.addEventListener('click', function (ev) {
    if (!menu.hidden && !menu.contains(ev.target)) closeMenu(false);
  });
  unlockToggle.addEventListener('click', function () {
    P.unlockAll = !P.unlockAll;
    save();
    syncUnlock();
    snackbar(P.unlockAll ? 'Усі уроки та іспит відкрито' : 'Уроки знову відкриваються по черзі');
    render(true);
  });
  qs('#reset-open').addEventListener('click', openReset);
  qsa('#app-menu a').forEach(function (a) { a.addEventListener('click', function () { closeMenu(false); }); });
  if (resetDialog) {
    qs('#reset-cancel').addEventListener('click', function () { resetDialog.close(); });
    qs('#reset-confirm').addEventListener('click', function () { resetDialog.close(); doReset(); });
  }

  /* ---------- keyboard ---------- */
  var INTERACTIVE_ROLES = /^(button|tab|row|gridcell|menuitem|option|treeitem|link|checkbox|switch|listitem)$/;
  document.addEventListener('keydown', function (ev) {
    if (ev.defaultPrevented || ev.altKey || ev.ctrlKey || ev.metaKey) return;
    if (qs('dialog[open]')) return;
    if (!menu.hidden) {
      if (ev.key === 'Escape') { ev.preventDefault(); closeMenu(true); }
      return;
    }
    var t = ev.target, tag = t && t.tagName;
    if (tag === 'INPUT' || tag === 'TEXTAREA' || tag === 'SELECT' || (t && t.isContentEditable)) return;
    if (ev.key === 'Enter') {
      if (tag === 'BUTTON' || tag === 'A' || tag === 'SUMMARY') return;
      if (t && t.getAttribute && INTERACTIVE_ROLES.test(t.getAttribute('role') || '')) return;
      if (keys.next) { ev.preventDefault(); keys.next(); }
    } else if (/^[1-9]$/.test(ev.key) && keys.choose) {
      if (keys.choose(Number(ev.key) - 1)) ev.preventDefault();
    }
  });

  /* ---------- router ---------- */
  function setNav(name) {
    qsa('.app-nav a').forEach(function (a) {
      if (a.getAttribute('data-nav') === name) a.setAttribute('aria-current', 'page');
      else a.removeAttribute('aria-current');
    });
  }

  function render(keepScroll) {
    cleanup();
    closeMenu(false);
    var parts = location.hash.replace(/^#\/?/, '').split('/').filter(Boolean).map(function (x) {
      try { return decodeURIComponent(x); } catch (e) { return x; }
    });
    var nav = 'modules', focusTarget;
    try {
      switch (parts[0]) {
        case undefined: nav = 'home'; focusTarget = viewHome(); break;
        case 'modules': focusTarget = viewModules(); break;
        case 'module': case 'm': focusTarget = viewModule(parts[1]); break;
        case 'lesson': case 'l': focusTarget = viewLesson(parts[1], parts[2]); break;
        case 'quiz': case 'q': focusTarget = viewQuiz(parts[1]); break;
        case 'exam': focusTarget = viewExam(); break;
        case 'sandbox': nav = 'sandbox'; focusTarget = viewSandbox(); break;
        case 'cheatsheet': nav = 'cheatsheet'; focusTarget = viewCheatsheet(); break;
        case 'glossary': nav = 'glossary'; focusTarget = viewGlossary(); break;
        case 'about': nav = 'about'; focusTarget = viewAbout(); break;
        default: nav = ''; focusTarget = viewNotFound();
      }
    } catch (err) {
      if (window.console) console.error(err);
      cleanup();
      nav = '';
      focusTarget = viewNotFound('Щось пішло не так', 'Не вдалося показати цю сторінку. Спробуй повернутися на головну.');
    }
    setNav(nav);
    if (!keepScroll) window.scrollTo(0, 0);
    if (!firstRender || parts.length) focusEl(focusTarget);
    firstRender = false;
  }
  var firstRender = true;

  window.addEventListener('hashchange', function () { render(false); });
  window.addEventListener('scroll', function () {
    if (topBar) topBar.classList.toggle('scrolled', window.scrollY > 4);
  }, { passive: true });

  hydrateIcons(document);
  syncUnlock();
  render(false);
  if (!storageOk) snackbar('Прогрес не зберігатиметься: сховище браузера недоступне');

  // Test hook (read-only introspection).
  window.CLI_APP = {
    normalizeCommand: normCmd,
    progress: function () { return JSON.parse(JSON.stringify(P)); },
    lessons: function () { return lessons.map(function (e) { return e.lesson.id; }); }
  };
})();
