window.CLI_COURSE = window.CLI_COURSE || { modules: [], exam: null, cheatsheet: null };
window.CLI_COURSE.exam = {
  id: "exam", title: "Фінальний іспит", passPercent: 80,
  quiz: [
    { title: "SSH", question: "Ти ввів на Mac `ssh stanislav@10.0.0.50`, попрацював і ввів `exit`. Де виконається наступна команда `ls`?", options: ["На Mac — SSH-сесію закрито", "На Pi — exit лише очищає екран", "Ніде: після exit термінал треба перезапустити"], correct: 0, feedback: "`exit` закриває SSH-сесію, і ти повертаєшся в Terminal Mac із запрошенням `%`." },
    { title: "SSH", question: "`ping -c 3 10.0.0.50` відповідає, а `ssh stanislav@10.0.0.50` пише `Connection refused`. Що перевірити?", options: ["Кабель живлення Pi", "Чи увімкнений SSH-сервер на Pi", "Чи не заповнена SD-карта"], correct: 1, feedback: "Pi в мережі (ping є), але порт 22 ніхто не слухає — SSH вимкнений. На Pi це видно в `ss -tulpn`." },
    { title: "bash", question: "Ти ввів `htop`, а bash відповів `command not found`. Найімовірніша причина?", options: ["Pi перегрілася", "Немає інтернету", "Програми немає в жодній папці з `PATH` — її не встановлено"], correct: 2, feedback: "Shell шукає програму в папках `PATH`. Не знайшов — `command not found`. Лікується `sudo apt install htop`." },
    { title: "Файли", question: "Ти в `~/projects/led-test` і хочеш прибрати папку `build` з вмістом, не ризикуючи зайвим. Що найобережніше?", options: ["`rm -rf ~/projects`", "Перевірити `pwd` і `ls`, потім `rm -ri build` або перейменувати в `build_old`", "`rmdir build`"], correct: 1, feedback: "`rm -rf` видаляє без кошика і без питань. `-i` питає про кожен файл, а перейменування взагалі нічого не знищує. `rmdir` не видалить непорожню папку." },
    { title: "Файли", question: "Що зробить `cd` без аргументів у bash на Pi?", options: ["Поверне в домашню папку `/home/stanislav`", "Покаже помилку «missing operand»", "Перейде в корінь `/`"], correct: 0, feedback: "`cd` без аргументу — те саме, що `cd ~`: домашня папка поточного користувача." },
    { title: "apt", question: "Навіщо запускати `sudo apt update` перед `sudo apt install`?", options: ["Щоб оновити всі програми", "Щоб перезавантажити Pi", "Щоб оновити списки пакетів — інакше apt може не знайти пакет або взяти застарілу версію"], correct: 2, feedback: "`update` лише оновлює списки доступних версій і нічого не встановлює. Оновлює програми `upgrade`." },
    { title: "Мережа", question: "`ping -c 3 8.8.8.8` працює, а `ping -c 3 google.com` пише, що ім'я не знайдено. Де проблема?", options: ["У DNS — імена не перетворюються на IP", "У кабелі — мережі немає", "У Wi-Fi-адаптері Pi"], correct: 0, feedback: "Інтернет за IP є, отже маршрут і шлюз у порядку. Не працює лише розв'язання імен — DNS." },
    { title: "Мережа", question: "Яка команда покаже шлюз за замовчуванням на Pi?", options: ["`hostname -I`", "`ip route`", "`rfkill list`"], correct: 1, feedback: "`ip route` показує рядок `default via 10.0.0.254 …` — це роутер. `hostname -I` дає лише адреси Pi." },
    { title: "Стан системи", question: "Pi 5 іноді перезавантажується під навантаженням, а `vcgencmd get_throttled` показує не `0x0`. Що перевірити першим?", options: ["Версію Python", "Кількість файлів у домашній папці", "Блок живлення і кабель, потім охолодження"], correct: 2, feedback: "Ненульове значення означає, що були недостатнє живлення або перегрів. На Pi 5 найчастіша причина — слабкий блок живлення." },
    { title: "Процеси", question: "Скрипт `main.py` завис. Який порядок дій найкоректніший?", options: ["`pgrep -f main.py` → `kill PID`, і лише якщо не допомогло — `kill -9 PID`", "Одразу `killall python3`", "`sudo reboot`"], correct: 0, feedback: "Звичайний `kill` дає процесу завершитися акуратно. `killall` зачепить усі Python-процеси, а reboot зупинить усе на Pi." },
    { title: "Python", question: "На Raspberry Pi OS Trixie `pip3 install requests` поза venv пише `externally-managed-environment`. Що робити?", options: ["Додати `--break-system-packages`", "Створити venv: `python3 -m venv .venv`, активувати і встановити там", "Встановити через `sudo pip3`"], correct: 1, feedback: "Система захищає системний Python від зламу. Правильно — venv для проєкту або `sudo apt install python3-requests`. Обхідні прапорці ризикують зламати ОС." },
    { title: "GPIO", question: "Старий приклад на RPi.GPIO не працює на Pi 5. Чим скористатися?", options: ["Нічим — GPIO на Pi 5 недоступні", "Прошити старішу ОС", "Бібліотекою `gpiozero` (на Pi 5 вона працює через `lgpio`)"], correct: 2, feedback: "На Pi 5 контакти обслуговує новий чип RP1, і RPi.GPIO з ним не працює. `gpiozero` — рекомендована бібліотека, а `pinctrl` допомагає з діагностикою." },
    { title: "GPIO", question: "Чому не можна подати 5 В від датчика прямо на контакт GPIO?", options: ["GPIO працюють з логікою 3,3 В — 5 В може пошкодити Pi", "GPIO приймають лише змінний струм", "5 В — це занадто мало для GPIO"], correct: 0, feedback: "Логіка GPIO — 3,3 В. Для 5-вольтових датчиків потрібен перетворювач рівнів, для реле — готовий модуль." },
    { title: "systemd", question: "Ти виконав `sudo systemctl enable my-service`, а `systemctl status` показує `inactive (dead)`. Чому?", options: ["enable зламав сервіс", "`enable` лише вмикає автозапуск при завантаженні; запускає зараз `start` або `enable --now`", "Треба перезавантажити Mac"], correct: 1, feedback: "`enable` ≠ `start`. `sudo systemctl enable --now my-service` робить обидва кроки однією командою." },
    { title: "systemd", question: "Ти змінив `/etc/systemd/system/my-service.service`. Що обов'язково зробити перед restart?", options: ["`sudo systemctl daemon-reload`", "`sudo apt update`", "`sudo reboot`"], correct: 0, feedback: "systemd кешує unit-файли. Без `daemon-reload` він працюватиме за старою версією і попередить про це в `status`." },
    { title: "Логи", question: "Сервіс падає одразу після старту. Яка команда найшвидше покаже причину?", options: ["`dmesg | tail -50`", "`df -h`", "`journalctl -u my-service -n 50`"], correct: 2, feedback: "Журнал конкретного сервісу покаже Traceback Python і код виходу. `dmesg` — про ядро і залізо, `df` — про диск." },
    { title: "Передача файлів", question: "Ти оновив код на Mac і хочеш передати на Pi лише змінене, а спершу побачити, що саме поїде. Що обрати?", options: ["`scp -r` двічі", "`rsync -av --dry-run ./led-test/ stanislav@raspberrypi.local:~/projects/led-test/`, потім те саме без `--dry-run`", "Флешку"], correct: 1, feedback: "`rsync` передає лише зміни, а `--dry-run` показує план без жодних змін. Команду запускають на Mac." },
    { title: "Безпечність", question: "Потрібно записати Raspberry Pi OS на нову SD-карту. Що найбезпечніше для новачка?", options: ["`sudo dd` на перший-ліпший `/dev/…`", "`sudo mkfs.ext4 /dev/mmcblk0` прямо на працюючій Pi", "Raspberry Pi Imager на Mac"], correct: 2, feedback: "Raspberry Pi Imager сам показує носії й налаштовує SSH та користувача. `dd` і `mkfs` безповоротно знищують дані, якщо переплутати пристрій." }
  ]
};
